### ISSUE TITLE
Cannot open "/Users/leo/.vim/session/.lms.vim" for writing

### ISSUE THREAD

**Issue by lccro** [dhruvasagar/vim-prosession#10]
My .vim directory is a symbolic link to one of my "dotfiles" subdirectories, so it's probably the reason why I see this on vim startup:

Error detected while processing function <SNR>44_Prosession:
line   22:
Vim(mksession):E190: Cannot open "/Users/leo/.vim/session/.lms.vim" for writing
Press ENTER or type command to continue

**Comment by dhruvasagar** [comment]
What's the path !? I too have symlinked .vim to one of my dotfiles subdirectories so that shouldn't be the problem, it's more likely to do with whether or not the path exists.

Make sure the path exists (the session folder).

**Comment by lccro** [comment]
So that's peculiar... It does exist:

```
─➤  ls -la ~/.vim/sessions
total 4
drwxr-xr-x 3 leo staff  102 Feb 10 12:17 .
drwxr-xr-x 6 leo staff  204 Feb 10 11:37 ..
-rw-r--r-- 1 leo staff 2175 Jun 17  2014 default.vim
```

**Comment by dhruvasagar** [comment]
So what's the path your running this on !? The error ending in '.lms.vim' looks a bit weird.

Also you could try invoking `:echo undofile(getcwd())` after you launch vim and tell me what that outputs ? In v0.5.0 I have changed the naming convention and have gone with a undofile style naming for the files.

**Comment by dhruvasagar** [comment]
Ah, it's looking for `session` directory, while you seem to have a `sessions` directory...Either you should override `g:prosession_dir`  or rename the directory to `session`

**Comment by lccro** [comment]
Doh, that was it. Just created the singular version and that did the trick.
Thanks anyway!
