### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by dagadbm** [dhruvasagar/vim-prosession#103]
This plugin is very slow when restoring the sessions as can be seen from this:

![image](https://user-images.githubusercontent.com/16737095/210271300-d94eb9a1-0238-43c9-b06f-65b6ff8c26fc.png)

Do you think there is a way to make the restoring of sessions faster?

**Comment by dhruvasagar** [comment]
@dagadbm Unfortunately this is almost entirely on vim itself, prosession is just loading / sourcing the session file created by vim.
