### ISSUE TITLE
Multiple files for a single directory

### ISSUE THREAD

**Issue by m42e** [dhruvasagar/vim-prosession#11]
It seems that sometimes the Plugin writes the session to a path similar to:

```%proj%someproj``` but sometimes
```%proj%someproj%``` will be used.

**Comment by dhruvasagar** [comment]
Can you give me an example ?
It should always be something like `%path%to%dir%name.vim` so not too sure about the extra `%` you mention or where it appears, it could be because of an additional `/` at the end of the path name I suppose.

**Comment by dhruvasagar** [comment]
Did you do this by using `:Prosession` with a new directory (for which a session doesn't exist already) !?

**Comment by m42e** [comment]
Oh, I missed the .vim at the end in my first post.

If I'm starting vim within a folder it creates the file without the extra ```%``` or ```/``` at the end. If I switch using Prosession it is added. 

I'm currently using it on a Win64 with cygwin on it.

**Comment by dhruvasagar** [comment]
It should now be consistent, kindly confirm.

**Comment by m42e** [comment]
Thanks.

**Comment by m42e** [comment]
Seems not to work:

```
Error detected while processing function <SNR>64_GetSessionFile..<SNR>64_GetSessionFileName..<SNR>64_GetDirName..<SNR>64_StripTrailingSlash:
line    1:
E121: Undefined variable: name
```

**Comment by m42e** [comment]
See #12

**Comment by dhruvasagar** [comment]
Ah typo :/, I should add tests.
