### ISSUE TITLE
Option to disable for given workdir

### ISSUE THREAD

**Issue by pbower** [dhruvasagar/vim-prosession#112]
Hi, 

This plugin's great, but if I launch neovim from the home directory ~/ it clogs that up with an existing session>

Would you consider adding a configuration option in the plugin to enable excluding a list of directories from triggering automatic save and/or reload?

Thanks

**Comment by dhruvasagar** [comment]
@pbower This is already supported with `:h g:prosession_ignore_dirs` or `:h g:prosession_ignore_expr`
