### ISSUE TITLE
Add possibility to take git branch into account

### ISSUE THREAD

**Issue by m42e** [dhruvasagar/vim-prosession#14]
It would be a great feature if it would be possible to take the branch of the directory into account.

So it will be easier to work in different branches.

A function like this should get you the current git branch.
```
function! GetCurrentGitBranch()
    return system("git symbolic-ref -q HEAD'")
endfunction
```

**Comment by dhruvasagar** [comment]
I have actually thought about this, but I think it's not needed.
Sessions work with buffers, and files on the filesystem. When you switch branches, the files on the file system are changed by git to represent those versions that are in the HEAD for that branch. So it doesn't impact the session flow much.

The only case is with files that aren't there in certain branches but are in some, which I guess we can live with.

**Comment by m42e** [comment]
But working in several branchen normally means working on different topics with a focus on some files in particular.

Just my 2 cent.

**Comment by dhruvasagar** [comment]
Ok, it does make sense, i'll add it as an optional feature which we can enable.

**Comment by m42e** [comment]
Great thanks.

**Comment by dhruvasagar** [comment]
Let me know what you think.

**Comment by m42e** [comment]
Please change the command for reading the branch to:
```
git rev-parse --abbrev-ref HEAD 2> /dev/null
```
To avoid error messages in folders without a repository.

Rest works as expected.

**Comment by dhruvasagar** [comment]
cool, will do!

**Comment by dhruvasagar** [comment]
>Added `g:prosession_branch_cmd` that can be set to work with other vcs
  besides git, set to default for git.
