### ISSUE TITLE
Prosession does not create the session files as indicated in the command line in Windows

### ISSUE THREAD

**Issue by nkmathew** [dhruvasagar/vim-prosession#18]
I can run it with this `Prosession cats` on startup and it'll name the session file **%Windows%system32.vim** which when auto-completed at a later time becomes **/Windows/system32**. 

All supplied session names are ignored and a percentage-escaped version of the current working directory used.

**Comment by dhruvasagar** [comment]
Hi, what's `cats` supposed to be ? As long as `cats` the argument to Procession is either an existing session or a valid path on the system it should work fine, if you want to just create named sessions, that's not something Prosession allows at the moment, you could very well just use `:Obsession` for that.

Kindly provide a slightly more detailed explanation of your expectation here, perhaps I could help you better / add it as a feature in Prosession.

**Comment by nkmathew** [comment]
Yes, I want named sessions. Obsession could do the work I guess, I just don't like the way it litters project folders with the session files and also it's lack of completion.

I wanted something like:  
+ cd to project folder
+ Run ```Prosession project-name```
+ Do stuff...
+ Run Prosession with different project name
+ Work on other project and so on

Such that the number of session files in ~/vim/session reflects the number of projects/things I'm working on at the time.
HTH

**Comment by dhruvasagar** [comment]
Prosession does support this already, but slightly differently.

* cd into project folder
* launch vim without any arguments -> Prosession starts a new session for the current project if one doesn't exist, if one does exist, it will continue recording for it.
* Do stuff...
* If you wanted to switch to another project for which a session was tracked by Prosession earlier, you can just type `:Prosession <Tab>` that will complete names of existing sessions by name of the directory, if one didn't exist already, simply start typing the complete path to the directory (which is also tab completed) and press enter in the end to start a new session.

**Comment by nkmathew** [comment]
That'll do. I've been using it for quite some time and never realized it worked that way. I used to create the session files manually in the session folder every time I did a new project.

If it's okay with you I'd like to present some feature requests:
+ Make it work with ```Prosession .```
+ Warn the user when the argument to the command does not point to a folder(e.g in my case)
+  Add a **ProsessionDelete** command

**Comment by dhruvasagar** [comment]
The first 2 actually make sense, I am not entirely sure what ProsessionDelete command should be doing though.

**Comment by nkmathew** [comment]
Deleting the session variables from VIm? Cause reading percentage signs is hard?

**Comment by dhruvasagar** [comment]
@nkmathew btw with Prosession ideally you would never have to actually look up the session files, that's one of the goals of Prosession. The completion with `Prosession` command shouldn't have any `%` signs.

And you can already just call `:Obsession!` to end the current session (and delete the session file), so I feel that isn't something that's required from Prosesion's perspective.

**Comment by nkmathew** [comment]
It's all good then. Thank for all the help

**Comment by dhruvasagar** [comment]
Np, will work towards the 2 features you requested, will link to this issue as I release them, thanks.

**Comment by nkmathew** [comment]
Hey @dhruvasagar, it's been almost a year. Did you get too tied up?

**Comment by dhruvasagar** [comment]
Hey, looks like I have been. I'll have a look again. #2 should be easy, #1 can be tricky.

**Comment by nkmathew** [comment]
Should I give up on this?

**Comment by dhruvasagar** [comment]
Hi, never give up :). Sorry for the delay, sometimes it's hard to keep track of 'pending' action items when there's too much to do.

The above referenced commit adds support for 1.

**Comment by nkmathew** [comment]
Haha, thanks man. Been waiting for this for years ... literally

**Comment by dhruvasagar** [comment]
The above commit reports an error if the argument supplied to `:Prosession` command is not an existing directory. Let me know if this is what you were looking for.

**Comment by dhruvasagar** [comment]
Cool i'll close the issue for now then, let me know if there's anything else. And thanks for your patience :).
