### ISSUE TITLE
Use session based on repo root (not cwd())

### ISSUE THREAD

**Issue by blueyed** [dhruvasagar/vim-prosession#19]
This could make use of https://github.com/dbakker/vim-projectroot to get the current repo root.

The idea is to only have a session per project, not for each of it's subdirs.

**Comment by dhruvasagar** [comment]
I understand where you are coming from, however I think this might be complexity we can avoid. How often do you find yourself in a situation where you are in a subdirectory of a project ?

**Comment by dhruvasagar** [comment]
Hey, I am going to close this at the moment, If there is adequate demand for it I can add this feature. But at the moment I feel it's complexity that we can avoid since it's a rare situation.
