### ISSUE TITLE
g:prosession_on_startup should not be triggered with `vim -t foo`

### ISSUE THREAD

**Issue by blueyed** [dhruvasagar/vim-prosession#20]
It uses `argc()`, which is `0` in that case.

(`-t foo` goes to tag `foo`)

**Comment by dhruvasagar** [comment]
Perhaps, but there is no elegant, platform agnostic way to detect such cli options from within vimscript. I am not sure how this would behave if you were to specify a filename just to avoid prosession to kick in, but I'd suggest to try that.

**Comment by dhruvasagar** [comment]
At the moment I am going to close this issue since it's not a pressing one and is hard to fix.
