### ISSUE TITLE
Invoking ":Prosession . " crashes neovim

### ISSUE THREAD

**Issue by malteneuss** [dhruvasagar/vim-prosession#23]
I can't get Prosession to work with neovim.  It doesn't seem to save or restore anything and when i invoke it manually with e.g. ":Prosession . " it crashes with the following error message:
```
Error detected while processing function <SNR>27_Prosession[8]..<SNR>27_GetSessionFile[1]..<SNR>27_GetSessionFileName[1]..<SNR>27_GetDirName:
line    2:
E121: Undefined variable: dir
E116: Invalid arguments for function s:StripTrailingSlash(dir)
E15: Invalid expression: s:StripTrailingSlash(dir)
line    6:
E121: Undefined variable: dir
E116: Invalid arguments for function s:undofile(dir)
E15: Invalid expression: s:undofile(dir)
```

**Comment by adarsh** [comment]
I get the same errors in regular terminal Vim, version 7.4 in iTerm.

**Comment by dhruvasagar** [comment]
`Procession .` Isn't valid usage. You have to provide either path or a project / session name used previously.

**Comment by dhruvasagar** [comment]
btw, there was a typo in a recent update, kindly update the plugin and try.

**Comment by adarsh** [comment]
Works now for me. Nice, thank you!
