### ISSUE TITLE
Command to overwrite existing session file

### ISSUE THREAD

**Issue by nikil** [dhruvasagar/vim-prosession#24]
First - thanks for writing this great plugin!  It's awesome.

I had a feature request.  Sometimes I have an existing "prosession" for a particular directory, and I want to replace it with a brand new session (that I opened with another vim in the same directory).  To do this I need to find the corresponding session file and delete it which is a little cumbersome.

Perhaps you could add a "Prosession! <file>" command that would forcibly overwrite this existing sesion file?

**Comment by dhruvasagar** [comment]
Hi, you're welcome.

You can use `:Obsession!` to kill the current session, and you could use `:Obsession` again to start another.
