### ISSUE TITLE
New session creates X empty buffers (where X is number of buffers from previous session)

### ISSUE THREAD

**Issue by mikeys** [dhruvasagar/vim-prosession#25]
1. Go to a project directory where you previously didn't have any vim session.
2. Type `vim` to start vim and create a session for this project
3. Quit vim (`:qall`), the session gets saved.
4. Go to a different directory where you previously didn't have any vim session
5. type `vim` to start vim and create a session for this project

As can be seen in the GIF below, after step 5 - three empty buffers are visible at the top until I open up a file (using Ctrl-P plugin in this case).

Can this be avoided somehow?
![vim-prosession](https://cloud.githubusercontent.com/assets/1187953/15857111/4716a378-2cc2-11e6-8bfe-8e786e743da1.gif)

**Comment by dhruvasagar** [comment]
I am actually not able to reproduce this issue at all. Kindly do the following additionally to what you are doing already and share the gifcast. (btw what did you use to create this gif ?)
* What are you using for the buffer list that comes on top ? (vim plugin)
* Kindly execute `:ls` the second time, when you launch vim from the second directory without session.
* Kindly execute `:echo v:this_session` to show me for certain there isn't a current session loaded / in progress. You can do this in both directories for comparison.

**Comment by mikeys** [comment]
@dhruvasagar never mind, you can close this. I was having `viminfo` set: 😃 
`set viminfo^=%`

Perhaps you'd want to add this to a FAQ section? (definitely not a must though)

**Comment by dhruvasagar** [comment]
Cool, i'll have a look at what side-effects may happen as a result of using `viminfo`, i'll add that to the README. Thanks.
