### ISSUE TITLE
prosession_default_session usage unclear

### ISSUE THREAD

**Issue by tomleo** [dhruvasagar/vim-prosession#26]
I would like to set my default session to `~/Dropbox` however it looks like in the help page the default value for `prosession_default_session` is 0. Does that imply that `prosession_default_session` is a Boolean that takes either `0` or `1`?

Is there currently a way to define the location/path of my default session? The usage for this setting is unclear to me.

Thanks!

**Comment by dhruvasagar** [comment]
Hi,

Kindly refer to the `:h prosession`.
The setting you're looking for is `g:prosession_dir`, that is where prosession saves / loads session files to / from.

**Comment by tomleo** [comment]
I guess I misunderstood what `default_session` meant. Is there a setting to define which session you want to use when starting vim?

Every time I start vim I type `:Prosession ~/Dropbox`, I thought `prosession_default_session` would define the default session to use when starting vim, not whether or not to use `'~/.vim/session/'` as the directory to store session files.

It seems redundant to both have a defined default for `g:prosession_dir` and a setting `g:prosession_default_session` that indicates whether or not you want to use that setting.

Am I misunderstanding the help file still? Hope I'm making sense and thanks for the quick response @dhruvasagar

**Comment by dhruvasagar** [comment]
The idea of a 'default' session is that when you start vim in a directory which does not already have a session for, it will load the default session (when g:prosession_default_session is enabled).

If you want prosession to start the session for Dropbox folder, then you should just launch vim from that folder. `Prosession <dir/name>` is designed to switch to a different session if you started with some other.

**Comment by dhruvasagar** [comment]
BTW the default session is literally named `default` for convenience. As of now there is no way to name this default session, although I don't really see the need for that. If you want to load a specific session you should just launch vim from within that directory.

**Comment by tomleo** [comment]
I'm using gvim, so adding `-c "cd ~/Dropbox"` did the trick. Thanks for your help @dhruvasagar!

**Comment by dhruvasagar** [comment]
You're welcome
