### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by astromac** [dhruvasagar/vim-prosession#32]
I recently updated my plugins and started receiving the following error on startup. Disabling prosession or deleting the session files makes the errors go away on startup.

```
Error detected while processing function <SNR>30_LeaveWin:
line 16:
E121: Undefined variable b:last_changedtick
Error detected while processing function <SNR>30_LeaveWin:
line 16:
E15: Invalid expression: b:changedtick > b:last_changedtick
```

Using Neovim v0.2.0-480-g25427ae8

**Comment by dhruvasagar** [comment]
Hi, this doesn't seem to be anything related to `vim-prosession`, perhaps something to do with some plugin / ftplugin that you may have removed recently, but left some stuff in session files somehow ?

After you remove the session file, and continue / start a new session do you get the error again ?

**Comment by astromac** [comment]
Yes.

**Comment by dhruvasagar** [comment]
Can you grep / ag / rg within your plugin directory for `LeaveWin`, `last_changedtick` and see where those exist ? Perhaps it's some plugin also doing something to sessions ?

**Comment by astromac** [comment]
Did as you asked and both searches hit on https://github.com/Konfekt/FastFold plugin. Removing the plugin and deleting the prosession files results in no errors upon startup.

**Comment by dhruvasagar** [comment]
Hi, i'll close this issue now since I believe it was resolved & was due to another plugin.
