### ISSUE TITLE
Implement list of sessions

### ISSUE THREAD

**Issue by alex-shamshurin** [dhruvasagar/vim-prosession#33]
Like bufferexplorer do and user can open needed project. Is it difficult?

**Comment by dhruvasagar** [comment]
Ah it's you, I was yet to see this ticket. It's not difficult to achieve.

**Comment by alex-shamshurin** [comment]
Would be nice to use it.

**Comment by alex-shamshurin** [comment]
Are there any updates with this issue? Integration with unite/denite?

**Comment by alex-shamshurin** [comment]
I found https://github.com/gikmx/ctrlp-obsession plugin. Closed
