### ISSUE TITLE
closed buffers reapper

### ISSUE THREAD

**Issue by mhainfarecom** [dhruvasagar/vim-prosession#34]
Hi
After update of vim-prosession every time when I'll close buffer (used with airline:tabline extension) and quit vim it reappear once I've start vim again.
In my session file next to badd ... I see entries like:
args dyd.txt
which is a cause of a problem.
Best
Mikolaj

**Comment by dhruvasagar** [comment]
Hi, well this is odd, but not prosession's fault. The session files are created by vim-obsession utilising the native `:mksession`. Also, when you close a file, it doesn't necessarily close / remove the buffer, for that you would have to do something like `:bw`or `:bd`.

**Comment by mhainfarecom** [comment]
Hi, thanks for explanation. I've found an issue - it is mac-vim which adds args when opening a file in same window. Currently there is no good solution for this, but as a workaround I'm opening files as new tab, and then I'm closing all tabs :-( This way I don't have args entries in session file and you plugin works correctly.
