### ISSUE TITLE
In windows this does not work

### ISSUE THREAD

**Issue by alex-shamshurin** [dhruvasagar/vim-prosession#35]
This error is still exists https://github.com/dhruvasagar/vim-prosession/issues/31. When I make new session  it saves session file without path, just the session name. When I try open it -  "Directory not found".

**Comment by dhruvasagar** [comment]
How do you make the new session ?

**Comment by alex-shamshurin** [comment]
`:Prosession <full path to project>`

**Comment by dhruvasagar** [comment]
I just tried it and it seems to be working as expected. Here are the steps I used to try to reproduce the issue :

* Prosession <full path to project without session>
* wq
* Prosession <full path to previous project> / cd to <full path to previous project>; vim

What are you doing different ?

**Comment by alex-shamshurin** [comment]
For what all these steps are? Just one step `:Prosession c:\User\alex\workspace\myproject` and project is created but path is wrong. The same is on Mac and Linux but it works as expected

**Comment by dhruvasagar** [comment]
I'll have to test on a windows box. Generally speaking it should work as long as the path itself exists and is correct.

**Comment by alex-shamshurin** [comment]
Path exists and correct, it has been autocompleted, so it's ok, and plugin creates a session file but when it's linux or mac the path contains full path with `%` symbols instead of slashes. On windows it creates a file which name is equal to last folder name, i.e. `myproject` with no path.

**Comment by dhruvasagar** [comment]
Try with the latest changes, it should work, if not, i'll have to debug on a windows machine. Will take a look later tonight.

**Comment by alex-shamshurin** [comment]
Ok, thanks.

**Comment by alex-shamshurin** [comment]
I does not work now at all. I updated plugin sources and what I get on startup:
![vim-prosession](https://cloud.githubusercontent.com/assets/1595209/26302507/20786ab0-3eed-11e7-8d91-f69bc97848df.jpg)

And in command mode `:Prosession <path to new project>` I get this:
![vim-prosession2](https://cloud.githubusercontent.com/assets/1595209/26302535/3f53a0e4-3eed-11e7-9332-9341d11339c8.jpg)

**Comment by dhruvasagar** [comment]
My bad, there was a typo in there, kindly try now.

**Comment by alex-shamshurin** [comment]
Oh, now it's OK, thanks a lot. Much obliged. But I'll make another ticket for new options.

**Comment by dhruvasagar** [comment]
Good to know, thanks!
