### ISSUE TITLE
shellslash breaks session filename generation in Windows

### ISSUE THREAD

**Issue by nkmathew** [dhruvasagar/vim-prosession#37]
It's assuming that  paths in Windows will always have backslashes:

```vim
function! s:undofile(cwd) "{{{1
  if has('win16') || has('win32') || has('win64')
    return substitute(a:cwd, '\', '%', 'g')
  else
    return substitute(a:cwd, '/', '%', 'g')
  endif
endfunction

```

**Comment by dhruvasagar** [comment]
Hi, that's right. I suppose I should use `&shellslash` value, although I am not entirely sure how wrong slashes behave on windows.

**Comment by nkmathew** [comment]
Or just replace both slashes with a regex, should work for most cases. It could probably fail for paths with spaces e.g. '/first/second/some\ folder' but if you're seriously doing that then you deserve to be bitten :)

**Comment by Grueslayer** [comment]
Both expand() and glob() will make the "right" slash from a mixed filename and escaped spaces and like dhruvasagar wrote, the shellslash option tells what kind of slash expand() and glob() is using.

**Comment by dhruvasagar** [comment]
Closing this issue for now, reopen if you face any issues.
