### ISSUE TITLE
Neither NerdTree nor Tagbar windows are being restored

### ISSUE THREAD

**Issue by Jeansen** [dhruvasagar/vim-prosession#38]
I use Nerdtree and Tagbar quite often. But whenever I close vim and want to continue on the previous session everything gets restored, except the windows for Nerdtree and Tagbar :(

**Comment by dhruvasagar** [comment]
Prosession's core job is really to facilitate centralised session file lookups based on the current working directory, all the remaining work of session handling is done by vim-obsession, making use of vim's `:mksession`.

In general I would recommend to move away from the habbit of having them open all the time.

There have been earlier reports of similar issues (https://github.com/tpope/vim-obsession/issues/5) but they haven't been dealt with for obvious reasons.

**Comment by Jeansen** [comment]
Oh, ok. Thanks for the info, anyway :smile:
