### ISSUE TITLE
session naming

### ISSUE THREAD

**Issue by briceburg** [dhruvasagar/vim-prosession#4]
I like the plugin -- especially keeping session files in a central location. The sha scheme is a bit confusing though -- do you think it's possible to adopt the file naming convention used by `undodir` ? it's a bit more readable and verbose.

Also does calling :Obsession pause the session recording/auto-updating as per tpotes plugin?

Thanks much!

**Comment by dhruvasagar** [comment]
Hi,

Well the plugin ensures that the naming scheme does not come in the way of the user. The completion ensures we complete only the names and not the rest of the bit. So I am not sure if we really need the naming convention used by `undodir`.

However I would surely not mind switching the naming convention per say. Originally I wanted to keep the naming convention configurable but didn't really get to doing it.

Prosession does not change / alter behavior of `Obsession`, it only leverage it. So yes calling `:Obsession` would stop the session record just like `tpope/vim-obsession` documents.

**Comment by dhruvasagar** [comment]
https://github.com/dhruvasagar/vim-prosession/pull/5 kinda improves upon session naming & usage (completion) for this use case. So makes things a lot better I guess. Kindly confirm if this is good enough for now.

**Comment by briceburg** [comment]
@dhruvasagar this is great. Thanks much!

**Comment by dhruvasagar** [comment]
Hi,

I have released v0.5.0, it isn't backwards compatible so you might require updating the old session files if you want to keep using them.

I have now switched to using undofile style format for the file names.
