### ISSUE TITLE
Does not cooperate with "vim-startify"

### ISSUE THREAD

**Issue by Grueslayer** [dhruvasagar/vim-prosession#40]
using this plugin vim-startify "mostly" does not work.

**Comment by dhruvasagar** [comment]
Hi, can you provide more details ? Was this issue resolved somehow ?

**Comment by Grueslayer** [comment]
Hi this needs multiple changes to work. If you work with session autoload in prosession, you will see the vim-startify startup buffer every second time you start. The problem is maybe something about vim-startify comes first, prosession second. After closing and session autosave the previously vim-startify buffer gots displayed by the next start (but I have not investigated this further).

Next problem is the autosave stuff in vim-startify, but that can be disabled.

If you start a session from the vim-startify list, it does nothing. I think vim-startify needs some code change using :Prosession to load the session.

The session list in vim-startify will list the files in the session folder as is, so you see the percent signs everywhere. 

I think there is to much work (mostly in vim-startify) to make both plugins work together with the seesion parts. 

What works is to disable autoloading in Prosession and all session stuff incl. session list/loading in vom-startify.

IMHO: default session folder should be expand('~\vimfiles\session') or expand('$HOME/vimfiles/session') etc. for has("win32") or has("win64"), also you can check with glob() for existance. Maybe some folders arent good for auto sessions (like /Windows/System etc.), this happens lot starting vim not from command line, maybe a global var with excludes can be a good idea.

Thank you for this plugin!

**Comment by Artem-Schander** [comment]
Hi folks

I thought instead of creating a new issue I post my two cents here, since both of you could be interested in it somehow and maybe even have a solution for my problem.

First of all, thanks @dhruvasagar for this plugin. I'm using it for years now. It does the job very well.

For a few weeks now I'm using vim-startify. I wrote [some scripts](https://github.com/Artem-Schander/dotfiles/blob/42e7dbea3ec5aa000251b47daa9e34f4d4b051ee/config/nvim/autoload/helpers/startify.vim#L11-L27) so it can be used with ProSession. Almost all "issues" mentioned by @Grueslayer are solved.

Here you can see my [ProSession config](https://github.com/Artem-Schander/dotfiles/blob/2efa7b8b3b5b69730d0ca7f8d8af0a0ad4171d11/config/nvim/init.vim#L717-L723) and my [Startify config](https://github.com/Artem-Schander/dotfiles/blob/2efa7b8b3b5b69730d0ca7f8d8af0a0ad4171d11/config/nvim/init.vim#L812-L850)

The result looks like this:
![2020-03-05-095027_479x241_scrot](https://user-images.githubusercontent.com/1243826/75964315-4c4f7500-5ec7-11ea-9689-87f387373fb8.png)

The session with the folder icon comes from ProSession and the one with the globe comes from Startify.

The only issue I could not find a solution for, is that ProSession (kind of) clears the session when I quit the Startify screen.

Steps to reproduce:
1. launch vim in a project folder
2. create a new session / select an existing session
3. open a file
4. execute `:SClose` (closes the session and shows Startify screen)
    At this point the session data is still there.
5. quit vim
    At this point ProSession (I assume that it is ProSession) writes an empty state into the session
6. launch vim
7. open previously used session
8. unexpected result: empty buffer

Hopefully there is help :)

**Comment by Grueslayer** [comment]
ProSession and Obsession both have no option to stop a session. So using SClose you need to tell at least obsession to stop updating the still active session.

Obession holds its session file name in a global var, still contains the file after SClose 

```vim
:echo g:this_obsession
```

**Comment by Artem-Schander** [comment]
Hi @Grueslayer 
Thanks for the answer.
Does that mean I have to override the :SClose command to unset g:this_obsession?

**Comment by dhruvasagar** [comment]
@Grueslayer @Artem-Schander 

> ProSession and Obsession both have no option to stop a session. So using SClose you need to tell at least obsession to stop updating the still active session.

That is not true, Obsession does have an option to stop session recording. Quoting the following from vim-obsession help documentation :

```
:Obsession              If session tracking is already in progress, pause it.
                        Otherwise, resume tracking or create a new session in
                        the current directory.
```

> 
> Obession holds its session file name in a global var, still contains the file after SClose
> 
> ```viml
> :echo g:this_obsession
> ```
> 
> And ProSession itself also has a var tells itself to save on quit, which is still active (and cant be changed without modifying Prosession)
> 
> ```viml
> s:save_last_on_leave
> ```

This can be controlled by setting `g:prosession_on_startup` which might be something you may want to leverage considering you want to use vim-startify on startup / launch instead and then switch into a project session from the startify screen.

Let me know what you guys think.

**Comment by Grueslayer** [comment]
>> ProSession and Obsession both have no option to stop a session. So using SClose you need to tell at least obsession to stop updating the still active session.
> 
> That is not true, Obsession does have an option to stop session recording. Quoting the following from vim-obsession help documentation :
> :Obsession              If session tracking is already in progress, pause it.
>                         Otherwise, resume tracking or create a new session in
>                         the current directory.

It's still true :( Like written in the manual (you quoted here) it PAUSES the session (v:this_session is empty but g:this_obesssion still contains its filename). And :Obession than restarts  the session (its a Toggle). So you do not have an option to really stop the session, you can only pause and restart and you have no option to force a stop while not knowing the internal implementation of obsession by v:this_session and g:this_obsession.

> This can be controlled by setting g:prosession_on_startup which might be something you may want to leverage considering you want to use vim-startify on startup / launch instead and then switch into a project session from the startify screen.
> Let me know what you guys think.

Its seems @Artem-Schander already did this, so something (maybe Obession) still writes the session to file. I'ven't tried to reproduce or fix the problem, but unset g:this_obsession seems to be a good first step.

**Comment by dhruvasagar** [comment]
@Grueslayer Yes, that's true, if you look at vim-obsessions' source, you can see that it relies on `g:this_obsession` to determine if the session should be captured. If you stop the session using `:Obsession` and then `:unlet g:this_obsession` it is effectively stopping the session capturing without deleting the session file.

**Comment by Artem-Schander** [comment]
Cool, thanks for the insight. I'll try it later :)

**Comment by roachsinai** [comment]
> Cool, thanks for the insight. I'll try it later :)

Hi, @Artem-Schander your solution is so greatttt! Thanks!!!

**Comment by roachsinai** [comment]
Hi, @Artem-Schander your solution is so greatttt! Thanks!!!

**Comment by dhruvasagar** [comment]
@Artem-Schander @roachsinai If this is something that works for you, would you be able to contribute to prosession by adding documentation for this workflow ? I have no qualms with startify and if prosession & startify can coexist amicably, that's good for everyone who wants to use both.

**Comment by roachsinai** [comment]
@dhruvasagar when open vim directly without given file, for vim-prosession will start a Session. While for startify it will open a startify buffer, list mru files (each file a entry) or other custom settings. So when both plugins enabled, startify will not work.

What @Artem-Schander did is set prosession not run on start up (by `let g:prosession_on_startup = 0`, when startup will only startify runs), but let start a prosession new session be an entry (or use the existed session) list in startify buffer.

Tish method also works with plugin `Plug 'vim-utils/vim-man'`, when you run `viman` to use vim open manpage files ([Using from the shell](https://github.com/vim-utils/vim-man#using-from-the-shell), vim-prosession will open a empty buffer or existed session again. What you need to do is change content in `/usr/bin/viman` to

```
#! /bin/bash
vim --cmd "let g:prosession_on_startup = 0" -c "Man $1 $2" -c 'silent only'
```

**Comment by Artem-Schander** [comment]
Hi everyone.
@roachsinai You're welcome. Nice to hear that it works for you.
@dhruvasagar Unfortunately, it didn't work well enough for me. I can not remember the reason for me giving up, but I think I'll give it another go and see if there is a suitable solution for my workflow. In this case I would be happy to contribute.

**Comment by dhruvasagar** [comment]
@Artem-Schander Cool, do share if something needs to change / improve in Prosession. In the meanwhile I might try taking a look as well. Thanks.

**Comment by Artem-Schander** [comment]
@dhruvasagar I think I have a solution without making too much compromises

> @Grueslayer Yes, that's true, if you look at vim-obsessions' source, you can see that it relies on `g:this_obsession` to determine if the session should be captured. If you stop the session using `:Obsession` and then `:unlet g:this_obsession` it is effectively stopping the session capturing without deleting the session file.

This helped a lot. I ended up overriding/complementing the commands [`SClose`](https://github.com/Artem-Schander/dotfiles/blob/67c7a5bb17615d26a5da1007d9eae503e4002daf/config/nvim/autoload/helpers/startify.vim#L85-L91) and [`SDelete`](https://github.com/Artem-Schander/dotfiles/blob/67c7a5bb17615d26a5da1007d9eae503e4002daf/config/nvim/autoload/helpers/startify.vim#L93-L99).
 The rest could remain [almost](https://github.com/Artem-Schander/dotfiles/blob/67c7a5bb17615d26a5da1007d9eae503e4002daf/config/nvim/init.vim#L886-L887) as it was.

> @Artem-Schander Cool, do share if something needs to change / improve in Prosession. In the meanwhile I might try taking a look as well. Thanks.

Initially I thought there could be something done in Prosession. Not starting the session on some (configurable) filetypes, or something similar. Autocmd seemed not to work as expected.
But now I don't think there is something left to do here. Maybe you have a different viewpoint.
I'm quite happy with the result and will surely use it from now on.

---
### Summary

1. [Configure Prosession](https://github.com/Artem-Schander/dotfiles/blob/67c7a5bb17615d26a5da1007d9eae503e4002daf/config/nvim/init.vim#L753-L759)
    - to not launch on vim startup
    - to use a specific path
```
let g:prosession_on_startup = 0
let g:prosession_last_session_dir = '~/.vim/session'
```
2. [Configure Startify](https://github.com/Artem-Schander/dotfiles/blob/67c7a5bb17615d26a5da1007d9eae503e4002daf/config/nvim/init.vim#L848-L890)
    - to use a the same path
    - to use some [custom functions](https://github.com/Artem-Schander/dotfiles/blob/67c7a5bb17615d26a5da1007d9eae503e4002daf/config/nvim/autoload/helpers/startify.vim#L93-L99) instead of the default ones
    - override the commands `SClose` and `SDelete`

```
let g:startify_session_dir = '~/.vim/session'

let g:startify_lists = [
\  { 'type': function('helpers#startify#listallsessions'), 'header': [ 'Sessions' ] },
\  { 'type': function('helpers#startify#startsession'), 'header': [ 'New Session' ] },
\  { 'type': 'dir', 'header': [ 'Files '. getcwd() ] },
\  { 'type': function('helpers#startify#listcommits'), 'header': [ 'Recent Commits' ] },
\  { 'type': 'bookmarks', 'header': [ 'Bookmarks' ] },
\  { 'type': 'commands', 'header': [ 'Commands' ] },
\ ]

cabbrev SClose call helpers#startify#stopsession()
cabbrev SDelete call helpers#startify#deletesession()
```
