### ISSUE TITLE
Plugin asking for vim-obsession, even though it's already installed and working

### ISSUE THREAD

**Issue by mrbig033** [dhruvasagar/vim-prosession#44]
I installed both using vim-plug. Obsession seems to work okay. I'm using NVIM v0.2.3-820-g9cefd83cc.

**Comment by dhruvasagar** [comment]
Can I see a screenshot or something ?

**Comment by blueyed** [comment]
I think it refers to https://github.com/dhruvasagar/vim-prosession/blob/3def4db2495a2c7e89ea681503dbb8fcfea8a4ae/plugin/prosession.vim#L9-L12, and can be reproduces by loading vim-prosession before vim-obession.

See https://github.com/dhruvasagar/vim-prosession/pull/46 for an improved msg.

**Comment by gpanders** [comment]
Why was this closed? I am having the same issue using vim's native package management. I have both `vim-prosession` and `vim-obsession` installed in my `.vim/pack` directory, but I get this error message every time I open vim or neovim.

**Comment by dhruvasagar** [comment]
Hi, I assumed it was no longer an issue so I had closed it.
Moreover, this issue should be resolved as long as you install obsession before prosession. If you're using vim-plug, something like this should also fix it `Plug 'tpope/vim-obsession' | Plug 'dhruvasagar/vim-prosession', you don't necessarily have to resort to doing so in an after plugin.

**Comment by dhruvasagar** [comment]
I will look into the same with regards to vim's native packaging tools

**Comment by gpanders** [comment]
> Hi, I assumed it was no longer an issue so I had closed it.
> Moreover, this issue should be resolved as long as you load / install obsession before prosession. If you're using vim-plug, something like this should also fix it `Plug 'tpope/vim-obsession' | Plug 'dhruvasagar/vim-prosession',` you don't necessarily have to resort to doing so in an after plugin.

Understood, however my concern was in regards to Vim's native package management which does not have any way to enforce ordering the way in which plugins are ordered. The one exception is that anything in the `after/` directory is guaranteed to load after all other plugins have loaded. Perhaps that can be taken advantage of in some way?

**Comment by dhruvasagar** [comment]
Right as far as I know vim's native package management does not allow for there to be some kind of dependency, the after plugin idea is a fitting solution.
I will add that to the documentation.
