### ISSUE TITLE
Error at nvim startup

### ISSUE THREAD

**Issue by berarma** [dhruvasagar/vim-prosession#54]
Hi. Thank you for this plugin. I've found a little issue.

I'm getting an error when starting nvim after updating this plugin to the latest code in master. I think it might be related to 1b0d02fc2318bf5977355e8bf50420f8e3b1195c.

I'm using Neovim 0.3.0.

This is the message:

> Error detected while processing /home/berarma/.config/nvim/plugged/vim-prosession/plugin/prosession.vim:
line    9:
E121: Undefined variable: g:prosession_on_startup
E15: Invalid expression: g:prosession_on_startup

I've fixed it by setting the variable ```g:prosession_on_startup``` on my init.vim but this wasn't needed before.

Thanks.

**Comment by dhruvasagar** [comment]
Thanks for pointing it out, I missed noticing this in the PR. Fixed it now.
