### ISSUE TITLE
procession doesn't set filetype for vimwiki buffers

### ISSUE THREAD

**Issue by Coleej** [dhruvasagar/vim-prosession#61]
When using prosession to restore a session with vimwiki buffers, the filetype is not automatically set. The correct filetype is set once you refocus on the window.

This doesn't seem to happen with standalone Obsession

**Comment by dhruvasagar** [comment]
I have recently been using vimwiki and tested this with both on startup as well as while switching between sessions. It is picking up the filetypes correctly.

Have you configured vimwiki to use a different extension than the default ?

@Coleej Let me know and i'll test it. Closing this issue for now.
