### ISSUE TITLE
Folder name with extension `.vim` works weird

### ISSUE THREAD

**Issue by markwu** [dhruvasagar/vim-prosession#64]
I have two folders:

```
/project/a-project.php
/project/b-project.vim
```

When I use `:Prosessions /project/a-project.php`, it will save session name `%project%a-project.php.vim`.  It is right.

But, when I use `:Prosessions /project/b-project.vim` it will save session name `b-project.vim` only. Is it expected behavior? I assume it should be `%project%b-project.vim.vim`

**Comment by markwu** [comment]
Hi, any update of this? Is it expected behavior?

**Comment by dhruvasagar** [comment]
Hi @markwu , I was testing this earlier, it's not exactly expected behavior it is a bug. The plugin makes some assumptions if the project name ends in `.vim` assuming it's a session file. I have a fix ready, I need to test it more before I can push it. Thanks for reporting.

**Comment by dhruvasagar** [comment]
@markwu I have fixed this and pushed in the latest release 1cb2eadde0b79f49eb4b5a54cc78735aea33cbca¬
