### ISSUE TITLE
Session files don't get generated with their paths when &shellslash is enabled in Windows

### ISSUE THREAD

**Issue by nkmathew** [dhruvasagar/vim-prosession#67]
Relevant: #37, #42 

```vim

function! s:undofile(cwd) "{{{1
  if (exists('+shellslash') && &shellslash) || has('win16') || has('win32') || has('win64')
    return substitute(a:cwd, '\', '%', 'g')
  else
    return substitute(a:cwd, '/', '%', 'g')
  endif
endfunction

```

The check for `shellslash` on Windows on that line becomes useless because of the following statements. The only time `getcwd()` will return paths with backslashes is when `&shellslash == 0` and given that Linux doesn't have it, the conditional should simply be:

```vim

  if exists('+shellslash') && !&shellslash
    return substitute(a:cwd, '\', '%', 'g')
  else
    return substitute(a:cwd, '/', '%', 'g')
  endif

```

**Comment by dhruvasagar** [comment]
@nkmathew Will you be able to test if I push this change on a separate branch ?

**Comment by nkmathew** [comment]
Yes I will

**Comment by dhruvasagar** [comment]
@nkmathew I have pushed the changes you suggested in the branch `fix-shellslash`. Kindly test it on windows and let me know, unfortunately I do not have access to a windows box right now.

**Comment by nkmathew** [comment]
It works. The session files are created with percentages in place of the slashes both with `shellslash` enabled and disabled

**Comment by dhruvasagar** [comment]
@nkmathew Thanks, I will merge and push this.
