### ISSUE TITLE
Cannot find directories ending with `.vim`

### ISSUE THREAD

**Issue by jandamm** [dhruvasagar/vim-prosession#71]
When I want to restore a session for a folder like `.../ctrlp.vim` it does not work because the session is saved as `...%ctrlp.vim` and therefore looking for the folder `.../ctrlp` which does not exist.

**Comment by dhruvasagar** [comment]
@jandamm Thanks, this issue has now been fixed in the latest release 1cb2eadde0b79f49eb4b5a54cc78735aea33cbca
