### ISSUE TITLE
Always use absolute path

### ISSUE THREAD

**Issue by nghialm269** [dhruvasagar/vim-prosession#72]
Hi,

Currently, `Prosession` create different session files if I run it with different parameters, although all of them resolve to the same folder.

For example, I have a project folder: `/home/nghialm/projects/personal/test`

* When I'm in `/home/nghialm/projects/personal/test` and I run `:Prosession .`, it will create `%home%nghialm%projects%personal%test.vim` in `g:prosession_dir`

* When I'm in `/home/nghialm/projects/personal` and I run `:Prosession test`, it will create `test.vim` in `g:prosession_dir`

* When I'm in `/home/nghialm/projects` and I run `:Prosession personal/test`, it will create `personal%test.vim` in `g:prosession_dir`

Is it possible to make `:Prosession path` resolve `path` to its absolute path before creating/loading the session file? So that wherever I run `:Prosession`, it would result in the same session file.

I'm using neovim master (neovim/neovim@e3afb30e6)

**Comment by dhruvasagar** [comment]
@mnrce i'll look into this
