### ISSUE TITLE
Allow to define certain directories to be ignored by Prosession

### ISSUE THREAD

**Issue by dhruvasagar** [dhruvasagar/vim-prosession#73]
I came up with the following `zsh` function as a working alternative, where `vim` is remapped so that:
1. When executed at the home directory, no auto-loading of Prosession shall occur,
2. When executed from other directories, Prosession will load automatically by default.

```
# This is a simple zsh function that remaps `vim` to be aware of where it is called
    # Note, the "$1" piece is necessary to have.
function vim() {
    if test $(pwd) = "/home/username"; then
        # excluding the home dir
        /usr/bin/vim --cmd "let g:prosession_on_startup=0" $1
    elif [ $(pwd) = "/home/username/Yet_another_dir" ]; then
        # excluding another dir
        /usr/bin/vim --cmd "let g:prosession_on_startup=0" $1
    # more directories can be added here :)
    else
        /usr/bin/vim $1
    fi
}
```

@dhruvasagar An option like `g:prosession_no_auto_start_dir` would be a more elegant solution.

_Originally posted by @llinfeng in https://github.com/dhruvasagar/vim-prosession/issues/68#issuecomment-706797600_

**Comment by dhruvasagar** [comment]
@llinfeng I have introduced `g:prosession_ignore_dirs` to allow configure a comma separated list of directories to be ignored by prosession. Let me know your thoughts.

**Comment by llinfeng** [comment]
Please advise if I am feeding in the "comma separate list of directories" to `g:prosession_ignore_dirs` wrong:
```
let g:prosession_ignore_dirs = [ "/home/llinfeng/", "/mnt/g/JMP"]
```
These are directories for a WSL distro on a Windows machine. And, I get the following error:
![image](https://user-images.githubusercontent.com/5890407/95699981-e15fdc80-0c13-11eb-9587-30e8fb4a1f20.png)

**Comment by dhruvasagar** [comment]
@llinfeng No, for some reason I chose for it to be a comma separated string `'/path1,/path2'`, let me switch it to an array, I was influenced by the likes of `wildignore`

**Comment by llinfeng** [comment]
Works great! The auto-compeletion following `:Prosession` rocks! It shall list all directories that `vim-prosession` knows of, which are the exact string-value needed for ignoring. Here is how I can excuse `prosession` from logging `gvim.exe` sessions started from WSL at its root dir.

---- 

* I assigned `powershell.exe -c "c:\Vim\vim82\gvim.exe"  $@ &` to an alias and launch `gvim.exe` from the WSL commandline frequently. Yet, procession auto-starts when I open GVIM this way.
* `vim-prosession` for GVIM loggs `%%wsl$%WLinux%home%llinfeng.vim` in its assigned dir. I want to exclude this directory using `g:prosession_ignore_dirs` but the spelling of the directory confused me.
* **Solution**: By tab-completing after issuing `:Prosession` in GVIM, I see that the logged session is "launched" from directory `//wsl$/WLinux/home/llinfeng`
![image](https://user-images.githubusercontent.com/5890407/95708581-a9b05f00-0c2a-11eb-8e70-7c4d0d92b9be.png)
* Adding an entry to `g:prosession_ignore_dirs` with the now deciphered dir solves the problem.

----

One follow up observation and an additional problem based on the following correspondence table:
| Windows Dir | ignore_string |
|---------|---------------|
| c:\TEMP | "c:/TEMP"     |
| d:\TEMP | "d:/TEMP"     |

* On Windows machines, it looks like `vim-prosession` does not care about the drive-letter, and saves the session into `%TEMP.vim` regardless of where GVIM is launched.
* **Problem**: When trying to open `gvim.exe` from subdirectories of the ignored directories, for example, `g:\TEMP\TempSub\`, the following error occurs. This is only happening for GVIM on Windows.

![image](https://user-images.githubusercontent.com/5890407/95709786-5ee41680-0c2d-11eb-8768-e4ee19f5f49d.png)

**Comment by dhruvasagar** [comment]
`:Prosession` auto-completion relies on pre-existing sessions in the sessions directory.

Regarding the issue on windows, i'll create a separate issue for that and try to fix it.

**Comment by dhruvasagar** [comment]
@llinfeng I am not exactly sure regarding the subdirectory error, it shouldn't be related to ignored directories feature. At the moment, that feature works only for directories and does not try to ignore all subdirectories. The error you've shown indicates it's a permissions issue (i.e. vim was unable to write a file to that location). Assuming sessions are other wise working for you, this could likely be because of the `C:` in the middle of the filename that may be the culprit. I will try to investigate this separately.
