### ISSUE TITLE
Unable to create session on Windows for subdirectory of ignored directory

### ISSUE THREAD

**Issue by dhruvasagar** [dhruvasagar/vim-prosession#75]
When trying to open `gvim.exe` from subdirectories of the ignored directories, for example, `g:\TEMP\TempSub\`, the following error occurs. This is only happening for GVIM on Windows. [Please take this as neutral documentation.]

![image](https://user-images.githubusercontent.com/5890407/95709786-5ee41680-0c2d-11eb-8768-e4ee19f5f49d.png)

_Originally posted by @llinfeng in https://github.com/dhruvasagar/vim-prosession/issues/73#issuecomment-706882783_

**Comment by llinfeng** [comment]
I can confirm that opening `gvim.exe` from other directories does create `*.vim` session files by default. This happened both in `powershell` and Command Prompt, launched with and without admin privileges.

**Comment by dhruvasagar** [comment]
I am going to close this for now since I am unable to reproduce this, if anyone else faces this again, we can reopen it.
