### ISSUE TITLE
Swap files

### ISSUE THREAD

**Issue by timsofteng** [dhruvasagar/vim-prosession#79]
Hello. I noticed vim create .swp file for every opened file with your plugin. 
Even if I do nothing inside the file.
Why does it happen?

**Comment by dhruvasagar** [comment]
i'll take a look

**Comment by dhruvasagar** [comment]
@timsofteng I have no reason to believe vim-prosession can cause this in any way. All we do is load vim sessions saved by vim-obsession and nothing else.
