### ISSUE TITLE
Disable auto create session

### ISSUE THREAD

**Issue by nguyentritai2906** [dhruvasagar/vim-prosession#82]
Most of the time I invoke `vim` I don't want to create a session unless I'm working on some project.
This behaviour is default in vim-obsession, that is, it only create session when I call `:Obsession`.
Is there anyway I can disable the auto create session behaviour?

**Comment by dhruvasagar** [comment]
@nguyentritai2906 I hope you discovered `g:prosession_on_startup` ? There's also `g:prosession_ignore_dirs` that you could make use of to ignore certain specific directories. Also there's `g:Prosession_ignore_expr`
