### ISSUE TITLE
Prosession stores mapping in last_session

### ISSUE THREAD

**Issue by eight04** [dhruvasagar/vim-prosession#83]
https://github.com/dhruvasagar/vim-prosession/blob/976f3e61c2dd4ab709ea5eccbbab9e42d35d7e8c/plugin/prosession.vim#L207
This behavior is inconsistent with Obsession:
https://github.com/tpope/vim-obsession/blob/82c9ac5e130c92a46e043dd9cd9e5b48d15e286d/plugin/obsession.vim#L76-L78

**Comment by dhruvasagar** [comment]
@eight04 I personally don't use this feature, however, this was designed to work specifically along with `g:prosession_last_session_dir` setting. The idea is for that directory we save and restore session in a custom way. I believe we can't rely on obsession for saving this at this stage.

Did you encounter an issue with this ? Can you please elaborate more on that ? Kindly share your thoughts / suggestions on this.

**Comment by eight04** [comment]
I set `g:prosession_last_session_dir` to `~` so gVim loads the last session automatically at startup. Did I misunderstand how this option works?

**Comment by dhruvasagar** [comment]
@eight04 No, that is right, although accidental because gVim always starts with `~` as the current directory. If you start gVim manually from the terminal while being in a different directory this does not apply.

**Comment by eight04** [comment]
How about changing `mksession` to something like this?
```vim
call writefile(["source ".path_to_current_session], path_to_last_session)
```
Though it won't work when `path_to_current_session == path_to_last_session`.

**Comment by dhruvasagar** [comment]
@eight04 I'll take a look, thanks for your suggestion.
