### ISSUE TITLE
Breaks loading items into quickfix with -q flag

### ISSUE THREAD

**Issue by Gee19** [dhruvasagar/vim-prosession#84]
When this plugin is installed/active it breaks the functionality of loading items into vim's quickfix list via the `-q` flag.

For example:
When using [git-jump](https://github.com/git/git/tree/master/contrib/git-jump), running `git jump grep vnoremap` results in quickfix items being loaded without filenames, see [screenshot.](https://i.imgur.com/KbLJCr3.png)

Piping the command to cat shows each match is formatted correctly:
```
git jump grep vnoremap | cat
vimrc:387:3:" vnoremap <silent> y y`]
vimrc:854:23: autocmd FileType qf vnoremap <buffer> d :'<,'>Reject<CR>
vimrc:856:23: autocmd FileType qf vnoremap <buffer> gk :'<,'>Keep<CR>
vimrc:863:1:vnoremap <leader>/ "ay:call TrimEscapeRegA()<CR>:Grep <C-r>a<CR>
```

Removing the entire `~/.vim/session/` directory has no effect.

Minimal vimrc:
```
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-obsession'
Plug 'dhruvasagar/vim-prosession'
call plug#end()
```

Removing or commenting out prosession solves the issue.

**Comment by dhruvasagar** [comment]
@Gee19 Thanks for reporting this, i'll need to take a look, never used this feature before.
