### ISSUE TITLE
E15: Invalid expression 

### ISSUE THREAD

**Issue by nf1s** [dhruvasagar/vim-prosession#87]
E15: Invalid expression: !argc() && len(v:argv) < 2 && g:prosession_on_startup

![Screenshot 2021-12-06 at 14 01 25](https://user-images.githubusercontent.com/21188670/144850574-cbd78674-7a1f-4668-8db8-06513e428692.png)

**Comment by ahmednafies** [comment]
When re installing the plugin I get

E121: Undefined variable: v:argv

**Comment by dhruvasagar** [comment]
@ahmednafies Thanks for reporting, this was added recently, can you tell us what version of vim you're on ?

**Comment by ahmednafies** [comment]
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by Gee19** [comment]
Looks like `v:argv` was added in NVIM 0.6

https://github.com/neovim/neovim/commit/e89462d9855eef7718d482df7f92da4279a1c5c3

@nf1s Can you try my fork and report back? https://github.com/Gee19/vim-prosession
