### ISSUE TITLE
Prosession always creates blank new session

### ISSUE THREAD

**Issue by dragon-architect** [dhruvasagar/vim-prosession#94]
I'm trying to figure out how to use Prosession, and when I invoke it on a session that has not yet been saved, it always wipes that session completely clean on me and creates a new blank session.

Current invocation attempts have included:
`:Prosession .` (I've since learned in skimming the closed issues that this is improper and not supported)
`:execute "Prosession " . getcwd()` (an attempt at not needing to remember the full directory path to my current working directory; seriously why can't Prosession just automatically get the current working directory if fed no input?)
`:Prosession /home/directory/rest/of/path/` (explicit path name this time, without relying on output from a builtin function)

In all three cases, the current session, which did not have a saved session, I should reiterate, because I'm trying to invoke Prosession to save and start tracking it, gets wiped clean and replaced with a blank, unnamed buffer.

Subsequently quitting and reopening vim results in, again, blank, unnamed buffer, and I have to manually reconstruct the session that I was attempting to begin tracking in the first place.

Current versions of vim that I use include:
```
calyodelphi@dragonpad:~/.vim$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32)
Included patches: 1-2269, 3612, 3625, 3669, 3741
...
calyodelphi@dragonpad:~/.vim$ gvim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32)
Included patches: 1-2269, 3612, 3625, 3669, 3741
```
Both running on Ubuntu Focal (20.04LTS)

**Comment by dhruvasagar** [comment]
@dragon-architect This is a bug, thanks for reporting.

**Comment by dhruvasagar** [comment]
@dragon-architect I have pushed a fix for this, also `:Prosession` can be invoked without any arguments to use the current working directory. Appears to be working well, if there are any issues do let me know. Thanks.

**Comment by dragon-architect** [comment]
There is definitely a new issue now after running `git pull` to update the plugin, but it's a different issue entirely that needs a separate ticket to be opened! 😄
