### ISSUE TITLE
g:loaded_prosession disables plugin if set to any value

### ISSUE THREAD

**Issue by dragon-architect** [dhruvasagar/vim-prosession#95]
Does what it says on the (issue's) tin! If `let g:loaded_prosession` exists at all--doesn't matter what its value is explicitly set to--it disables the plugin entirely.

Replication steps:
`let g:loaded_prosession = 0` in vimrc. Plugin disabled, as documented.
`let g:loaded_prosession = 1` (default value as documented) in vimrc. Plugin still disabled.
`"let g:loaded_prosession = 1` (commented out) in vimrc. Plugin works because variable does not even exist.

**Comment by dragon-architect** [comment]
Relatedly, `g:prosession_on_startup` also doesn't seem to work properly, either. Might be a separate issue but might also be related to this one if the same kind of variable check is being used on both.

**Comment by dhruvasagar** [comment]
This is by design, it's meant to avoid vim to load the plugin file multiple times but if set by the user it can be used to disable the plugin.

**Comment by dhruvasagar** [comment]
NOTE: It's not meant for the user.

**Comment by dhruvasagar** [comment]
@dragon-architect

**Comment by dragon-architect** [comment]
Oh, so this variable is set internally by prosession when it's first loaded so that it doesn't get loaded repeatedly?

**Comment by dhruvasagar** [comment]
@dragon-architect yes, and this is typically done by all plugins as a convention.

**Comment by dhruvasagar** [comment]
@dragon-architect Kindly open a separate issue for `g:prosession_on_startup` and I can take a look

**Comment by dragon-architect** [comment]
@dhruvasagar Done! Sorry for the delay. I'm terrible at getting around to things, ehe.
