### ISSUE TITLE
Unique viminfo per session

### ISSUE THREAD

**Issue by jrudess** [dhruvasagar/vim-prosession#98]
Thanks for this plugin -- been using it for quite a long time now.   I typically run a separate instance of vim for every session, from a different repo-root.   One issue I have is that the 'viminfo' file is still shared across all these instances so I often get my command-line and search-histories corrupted with data from a different session.

Similar to the 'undo' file support, could prosession add an option to setup a unique viminfo file per session?
```
:set viminfo+=path/to/custom/viminfo
```

**Comment by dhruvasagar** [comment]
@jrudess I will look into this, sounds like a good idea.
